Questions/exams/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('provas.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

Questions/provas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('exibir_prova/<int:prova_id>/', views.exibir_prova, name='exibir_prova'),
    path('resultados/', views.resultados_prova, name='resultados_prova'),
    path('excluir-pergunta/<int:pergunta_id>/', views.excluir_pergunta, name='excluir_pergunta'),
]

Questions/provas/models.py
from django.db import models

class Prova(models.Model):
    nome = models.CharField(max_length=300)

    def __str__(self):
        return self.nome

class Pergunta(models.Model):
    prova = models.ForeignKey(Prova, on_delete=models.CASCADE)
    texto = models.TextField()
    imagem = models.ImageField(upload_to='media/perguntas/', blank=True, null=True)

    def __str__(self):
        return self.texto

    def texto_formatado(self):
        return self.texto.replace('\n', '<br>')

class Resposta(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=800)
    correta = models.BooleanField(default=False)

    def __str__(self):
        return self.texto

    def texto_formatado(self):
        return self.texto.replace('\n', '<br>')

Questions/provas/forms.py
from django import forms
from .models import Prova

class ProvaSelectForm(forms.Form):
    prova = forms.ModelChoiceField(queryset=Prova.objects.all().order_by('-id'), empty_label=None)

Questions/provas/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Pergunta, Prova
from .forms import ProvaSelectForm
import random
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required


def index(request):
    if request.method == 'POST':
        form = ProvaSelectForm(request.POST)
        if form.is_valid():
            prova_id = form.cleaned_data['prova'].id
            url = reverse('exibir_prova', args=[prova_id])
            return redirect(url)
    else:
        form = ProvaSelectForm()

    return render(request, 'index.html', {'form': form})

"""
def exibir_prova(request, prova_id):
    prova = Prova.objects.get(id=prova_id)
    perguntas = Pergunta.objects.filter(prova=prova)
    return render(request, 'exibir_prova.html', {'prova': prova, 'perguntas': perguntas})
"""
def exibir_prova(request, prova_id):
    prova = Prova.objects.get(id=prova_id)
    perguntas = prova.pergunta_set.all().order_by('?')  # Ordena as perguntas de forma aleatória

    context = {
        'prova': prova,
        'perguntas': perguntas,
    }

    return render(request, 'exibir_prova.html', context)

def resultados_prova(request):
    corretas = request.GET.get('corretas')
    incorretas = request.GET.get('incorretas')
    nao_respondidas = request.GET.get('naoRespondidas')

    return render(request, 'resultados.html', {
        'corretas': corretas,
        'incorretas': incorretas,
        'nao_respondidas': nao_respondidas,
    })

@login_required
def excluir_pergunta(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, id=pergunta_id)
    if request.method == 'POST':
        # Excluir a pergunta
        pergunta.delete()
        # Redirecionar de volta para a página de exibição da prova
        return redirect('exibir_prova', prova_id=pergunta.prova.id)
    # Se o método da requisição não for POST, renderize uma página de erro ou redirecione para outra página

Questions/provas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title%}AOD{%endblock%}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="{% static 'provas/style.css' %}" rel="stylesheet">
  <script src="{% static 'provas/script.js' %}"></script>
</head>
<body>
  <header class="bg-dark text-white py-1 py-md-1 py-lg-1 fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor"
            class="bi bi-house-door-fill" viewBox="0 0 16 16">
            <path
              d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5" />
          </svg>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          {% block nav %}
          {% endblock %}
        </div>
      </div>
    </nav>
  </header>
  <main class="py-4">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="bg-dark text-white py-3">
    <div class="container text-center">
      <p class="m-0">&copy; AlexDeitos - 2023<i class="bi bi-house-door"></i></p>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Questions/provas/templates/exibir_prova.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Perguntas e Respostas{% endblock %}
{% block nav %}
<i class="bi bi-house-door-fill"></i>
<button class="btn btn-light" id="scroll-to-top">Início</button>
<button class="btn btn-light" id="scroll-to-bottom">Final</button>
<button class="btn btn-success" id="enviar-respostas">Enviar Respostas</button>
<button class="btn btn-danger" id="limpar-respostas">Limpar Respostas</button>
<img src="{{ MEDIA_URL }}/media/media/future.webp" alt="future" class="img-fluid future" style="max-height: 50px;"
    id="future">
{% endblock %}
{% block content %}
<div class="container">
    <h1 class="row col-10 mx-auto titulo-prova">{{ prova.nome }}</h1>
    <div id="perguntas">
        {% for pergunta in perguntas %}
        <div class="pergunta">
            {% if user.is_authenticated %}
            <form action="{% url 'excluir_pergunta' pergunta.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Excluir Pergunta</button>
            </form>
            {% endif %}
            <h2>{{ pergunta.texto_formatado|safe }}</h2>
            {% if pergunta.imagem %}
            <img src="{{ pergunta.imagem.url }}" alt="Imagem da pergunta">
            {% endif %}
            <!-- Renderizar respostas -->
            {% for resposta in pergunta.resposta_set.all %}
            <div class="resposta">
                <label>
                    <input type="checkbox" name="{{ pergunta.id }}" value="{{ resposta.id }}"
                        {% if resposta.correta %}data-correta="true" {% endif %}>
                    <span style="font-size:25px;line-height: 1.2;"
                        id="resposta-label-{{ pergunta.id }}-{{ resposta.id }}"
                        class="resposta-label {% if resposta.correta %}correta{% endif %}">{{ resposta.texto_formatado|safe }}</span>
                </label>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    <div class="text-center">
        <button class="btn btn-primary" id="pergunta-anterior">Pergunta Anterior</button>
        <button class="btn btn-primary" id="proxima-pergunta">Próxima Pergunta</button>
        <button class="btn btn-success" id="marcar-respostas">Validar Respostas</button>
        <button class="btn btn-danger" id="limpar-respostas1">Limpar Respostas</button>
        <!-- Botão para excluir a pergunta -->

    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const perguntas = document.querySelectorAll('.pergunta');
        let perguntaAtual = 0;

        // Função para mostrar a pergunta atual
        function mostrarPerguntaAtual() {
            perguntas.forEach((pergunta, index) => {
                if (index === perguntaAtual) {
                    pergunta.style.display = 'block';
                } else {
                    pergunta.style.display = 'none';
                }
            });

            // Habilitar ou desabilitar o botão "Pergunta Anterior" com base na pergunta atual
            const perguntaAnteriorBtn = document.getElementById('pergunta-anterior');
            perguntaAnteriorBtn.disabled = perguntaAtual === 0; // Desabilita o botão na primeira pergunta
        }

        // Mostrar a primeira pergunta ao carregar a página
        mostrarPerguntaAtual();

        // Ouvinte de evento para o botão "Próxima Pergunta"
        const proximaPerguntaBtn = document.getElementById('proxima-pergunta');
        proximaPerguntaBtn.addEventListener('click', () => {
            perguntaAtual = (perguntaAtual + 1) % perguntas.length;
            mostrarPerguntaAtual();
        });

        // Ouvinte de evento para o botão "Pergunta Anterior"
        const perguntaAnteriorBtn = document.getElementById('pergunta-anterior');
        perguntaAnteriorBtn.addEventListener('click', () => {
            if (perguntaAtual > 0) {
                perguntaAtual--; // Decrementa o índice da pergunta atual
            }
            mostrarPerguntaAtual();
        });
    });
</script>
{% endblock %}

Questions/provas/templates/index.html
{% extends 'base.html' %}

{% block title %}Perguntas e Respostas{% endblock %}

{% block content %}
  <div class="container mt-12 d-flex justify-content-center"> <!-- Adiciona classe d-flex e justify-content-center -->
    <div class="row">
      <div class="col-12">
        <h1 class="text-center col-12">Escolha a prova</h1>
        <form method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary col-12">Selecionar Prova</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Questions/provas/templates/resultados.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Resultados da Prova{% endblock %}
{% block content %}
    <h1>Resultados da Prova</h1>

    <!-- Iterar sobre todas as perguntas -->
    {% for pergunta in perguntas %}
        <h2>{{ pergunta.texto_formatado|safe }}</h2>
        <!-- Iterar sobre as respostas da pergunta -->
        {% for resposta in pergunta.resposta_set.all %}
            <div>
                {% if resposta.id in corretas %}
                    <span style="color: blue;">{{ resposta.texto_formatado|safe }}</span>
                {% elif resposta.id in incorretas %}
                    <span style="color: red;">{{ resposta.texto_formatado|safe }}</span>
                {% else %}
                    {{ resposta.texto_formatado|safe }}
                {% endif %}
            </div>
        {% endfor %}
    {% endfor %}
    
    <!-- Exibir resumo dos resultados -->
    <p>Corretas: {{ corretas }}</p>
    <p>Incorretas: {{ incorretas }}</p>
    <p>Não Respondidas: {{ nao_respondidas }}</p>
{% endblock %}